clc
clear


%% setup a testsuite for basic math operations
suite_basicMath = testsuite({'test_plus',...
                             'test_times', ...
                             'test_mtimes', ...
                             'test_poly2basis',...
                             'test_kron',...
                             'test_power',...
                             'test_prod',...
                             'test_transpose',...
                             'test_mrdivide',...
                             'test_rdivide',...
                             'test_sum',...
                             'test_dot',...
                             'test_remove_coeffs',...
                             'test_is_linear',...
                             'test_mpower',...
                             'test_nabla',...
                             'test_subs'});

% run the tests
results_suite_basicMath = run(suite_basicMath);


if  all([results_suite_basicMath.Passed])
    disp('Passed all test for basic polynomial math operations.')
else
  
end




