function f = pendulum_dyn_n2(in1,tau1)
%PENDULUM_DYN_N2
%    F = PENDULUM_DYN_N2(IN1,TAU1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Feb-2025 08:13:59

dtheta1 = in1(3,:);
dtheta2 = in1(4,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = theta2.*-1.0;
t6 = -theta2;
t7 = t4+theta1;
t9 = t6+theta1;
t8 = cos(t7);
t10 = sin(t9);
t11 = (dtheta1.*t10)./4.0;
t12 = (dtheta2.*t10)./4.0;
t13 = dtheta1.*t10.*(3.0./4.0);
t14 = dtheta2.*t10.*(3.0./4.0);
t15 = t11+t14;
t16 = t12+t13;
f = [dtheta1;dtheta2;t2.*1.9629196875e+1-dtheta2.*t15.*1.333958333333333+t8.*(t3.*(9.81e+2./2.0e+2)+tau1+dtheta1.*t16).*5.0e-1;t3.*1.638065625+tau1.*3.339583333333333e-1+dtheta1.*t16.*3.339583333333333e-1+t8.*(t2.*1.4715e+1-dtheta2.*t15).*5.0e-1];
end
