function f_sym_ctrl = pendulum_dyn_ctrl_n2(in1)
%PENDULUM_DYN_CTRL_N2
%    F_SYM_CTRL = PENDULUM_DYN_CTRL_N2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Feb-2025 08:14:00

dtheta1 = in1(3,:);
dtheta2 = in1(4,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = -theta2;
t5 = t4+theta1;
t6 = cos(t5);
t7 = sin(t5);
t8 = (dtheta1.*t7)./4.0;
t9 = (dtheta2.*t7)./4.0;
t10 = dtheta1.*t7.*(3.0./4.0);
t11 = dtheta2.*t7.*(3.0./4.0);
t12 = t8+t11;
t13 = t9+t10;
et1 = dtheta1.*(-1.035028689389086e+1)+dtheta2.*4.731845220881568+t3.*1.638065625-theta1.*3.859922394820199e+1+theta2.*3.369606860563877e-2;
et2 = dtheta1.*t13.*3.339583333333333e-1+(t6.*(t2.*1.4715e+1-dtheta2.*t12))./2.0;
mt1 = [dtheta1;dtheta2];
mt2 = [t2.*1.9629196875e+1+(t6.*(dtheta1.*(-3.099274927677862e+1)+dtheta2.*1.416896884605834e+1+t3.*(9.81e+2./2.0e+2)-theta1.*1.155809575492012e+2+theta2.*1.008990201541273e-1+dtheta1.*t13))./2.0-dtheta2.*t12.*1.333958333333333];
mt3 = [et1+et2];
f_sym_ctrl = [mt1;mt2;mt3];
end
