function f = pendulum_dyn_n3(in1,in2)
%PENDULUM_DYN_N3
%    F = PENDULUM_DYN_N3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Feb-2025 08:14:01

dtheta1 = in1(4,:);
dtheta2 = in1(5,:);
dtheta3 = in1(6,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = sin(theta3);
t5 = theta2.*-1.0;
t7 = theta3.*-1.0;
t9 = -theta2;
t10 = -theta3;
t11 = t5+theta1;
t12 = t7+theta1;
t13 = t7+theta2;
t17 = t9+theta1;
t18 = t10+theta1;
t19 = t10+theta2;
t23 = t2.*(9.81e+2./4.0e+1);
t25 = t4.*(9.81e+2./2.0e+2);
t26 = t3.*1.4715e+1;
t14 = cos(t11);
t15 = cos(t12);
t16 = cos(t13);
t20 = sin(t17);
t21 = sin(t18);
t22 = sin(t19);
t24 = -t23;
t27 = (dtheta1.*t21)./4.0;
t28 = dtheta1.*t20.*(3.0./4.0);
t29 = dtheta1.*t21.*(3.0./4.0);
t30 = dtheta2.*t20.*(3.0./4.0);
t31 = (dtheta2.*t22)./4.0;
t32 = (dtheta3.*t21)./4.0;
t33 = (dtheta3.*t22)./4.0;
t34 = dtheta2.*t22.*(3.0./4.0);
t35 = dtheta3.*t21.*(3.0./4.0);
t36 = dtheta3.*t22.*(3.0./4.0);
t37 = dtheta1.*t20.*(9.0./4.0);
t38 = dtheta2.*t20.*(9.0./4.0);
t39 = t27+t35;
t40 = t29+t32;
t41 = t31+t36;
t42 = t33+t34;
t43 = t28+t38;
t44 = t30+t37;
t45 = dtheta1.*t40;
t46 = dtheta3.*t39;
t47 = dtheta2.*t42;
t48 = dtheta3.*t41;
t49 = dtheta1.*t44;
t50 = dtheta2.*t43;
t51 = -t48;
t52 = t24+t46+t50;
t53 = t25+t45+t47+tau2;
t54 = t26+t49+t51+tau1;
f = [dtheta1;dtheta2;dtheta3;t2.*5.7240328125e+1-t46.*2.333958333333333-t50.*2.333958333333333+t14.*t54.*1.5+t15.*t53.*5.0e-1;t3.*1.9629196875e+1-t48.*1.333958333333333+t49.*1.333958333333333+tau1.*1.333958333333333-t14.*t52.*1.5+t16.*t53.*5.0e-1;t4.*1.638065625+t45.*3.339583333333333e-1+t47.*3.339583333333333e-1+tau2.*3.339583333333333e-1-t15.*t52.*5.0e-1+t16.*t54.*5.0e-1];
end
