function f = pendulum_dyn_n1(in1,in2)
%PENDULUM_DYN_N1
%    F = PENDULUM_DYN_N1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Sep-2024 17:46:11

dtheta1 = in1(2,:);
theta1 = in1(1,:);
f = [dtheta1;sin(theta1).*1.638065625];
end
