function z = build_monomials(degmat,indets)
% Build a monomial sparsity pattern.

% number of monomials
nt = size(degmat,1);

% set output
z = casos.package.core.PolynomialSparsity( ...
                           casadi.Sparsity.dense(nt,1), ...
                           sparse(degmat), ...
                           indets, ...
                           [1 1] ...
);

end
