function p = blockcat(a,b,c,d)
% Block concatenate polynomials.

p = a.new_poly;

% concatenate coefficient matrices
[S,p.coeffs] = coeff_blkcat(a.get_sparsity, ...
                            b.get_sparsity, ...
                            c.get_sparsity, ...
                            d.get_sparsity, ...
                            a.coeffs, ...
                            b.coeffs, ...
                            c.coeffs, ...
                            d.coeffs ...
);

% set sparsity
p = set_sparsity(p,S);

end
