function f = pendulum_dynamics(in1,in2)
%PENDULUM_DYNAMICS
%    F = PENDULUM_DYNAMICS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    31-Jul-2024 16:25:47

dtheta1 = in1(4,:);
dtheta2 = in1(5,:);
dtheta3 = in1(6,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = sin(theta3);
t5 = dtheta1.^2;
t6 = dtheta2.^2;
t7 = dtheta3.^2;
t8 = -theta2;
t9 = -theta3;
t10 = t8+theta1;
t11 = t9+theta1;
t12 = t9+theta2;
t13 = cos(t10);
t14 = cos(t11);
t15 = cos(t12);
t16 = sin(t10);
t17 = sin(t11);
t18 = sin(t12);
t19 = t13.^2;
t20 = t14.^2;
t21 = t15.^2;
t25 = dtheta2.*dtheta3.*t15.*t18.*1.34436e+9;
t26 = dtheta2.*dtheta3.*t13.*t14.*t18.*8.64e+8;
t27 = t13.*t14.*t15.*8.2944e+10;
t22 = t20.*3.688128e+10;
t23 = t21.*6.452928e+10;
t24 = t19.*8.309952e+10;
t28 = -t27;
t29 = t22+t23+t24+t28-1.14987692827e+11;
t30 = 1.0./t29;
et1 = t2.*1.0068992829e+10-t3.*t13.*6.79338576e+9-t4.*t14.*3.01504464e+9-t6.*t16.*9.2376081e+8-t2.*t21.*5.65056e+9-t7.*t17.*3.0792027e+8-t13.*tau1.*4.61664e+8-t14.*tau2.*6.14688e+8-dtheta1.*dtheta2.*t16.*3.0792027e+8-dtheta1.*dtheta3.*t17.*1.0264009e+8+t3.*t14.*t15.*3.390336e+9+t4.*t13.*t15.*3.390336e+9-t5.*t13.*t16.*1.038744e+9-t5.*t14.*t17.*4.61016e+8;
et2 = t6.*t14.*t18.*-4.61016e+8+t7.*t13.*t18.*3.46248e+8+t6.*t16.*t21.*5.184e+8+t7.*t17.*t21.*1.728e+8+t13.*t15.*tau2.*6.912e+8+t14.*t15.*tau1.*2.304e+8-dtheta1.*dtheta2.*t13.*t16.*3.46248e+8-dtheta1.*dtheta3.*t14.*t17.*1.53672e+8+dtheta2.*dtheta3.*t13.*t18.*1.15416e+8-dtheta2.*dtheta3.*t14.*t18.*1.53672e+8+dtheta1.*dtheta2.*t16.*t21.*1.728e+8+dtheta1.*dtheta3.*t17.*t21.*5.76e+7+t5.*t13.*t15.*t17.*5.184e+8+t5.*t14.*t15.*t16.*5.184e+8;
et3 = t6.*t13.*t15.*t18.*5.184e+8-t7.*t14.*t15.*t18.*1.728e+8+dtheta1.*dtheta2.*t14.*t15.*t16.*1.728e+8+dtheta1.*dtheta3.*t13.*t15.*t17.*1.728e+8+dtheta2.*dtheta3.*t13.*t15.*t18.*1.728e+8-dtheta2.*dtheta3.*t14.*t15.*t18.*5.76e+7;
et4 = t3.*5.2851597687e+10-t25+t26+tau1.*3.5916818e+9-t2.*t13.*5.6611548e+10-t4.*t15.*2.63763432e+10+t5.*t16.*8.08128405e+9-t3.*t20.*1.695168e+10-t7.*t18.*2.69376135e+9-t15.*tau2.*5.37744e+9-t20.*tau1.*1.152e+9+dtheta1.*dtheta2.*t16.*2.69376135e+9-dtheta2.*dtheta3.*t18.*8.9792045e+8+t2.*t14.*t15.*2.82528e+10+t4.*t13.*t14.*1.695168e+10;
et5 = t6.*t13.*t16.*5.19372e+9-t5.*t15.*t17.*4.03308e+9+t7.*t13.*t17.*1.73124e+9-t6.*t15.*t18.*4.03308e+9-t5.*t16.*t20.*2.592e+9+t7.*t18.*t20.*8.64e+8+t13.*t14.*tau2.*3.456e+9+dtheta1.*dtheta2.*t13.*t16.*1.73124e+9+dtheta1.*dtheta3.*t13.*t17.*5.7708e+8-dtheta1.*dtheta3.*t15.*t17.*1.34436e+9-dtheta1.*dtheta2.*t16.*t20.*8.64e+8+dtheta2.*dtheta3.*t18.*t20.*2.88e+8+t5.*t13.*t14.*t17.*2.592e+9;
et6 = t6.*t13.*t14.*t18.*2.592e+9-t6.*t14.*t15.*t16.*2.592e+9-t7.*t14.*t15.*t17.*8.64e+8-dtheta1.*dtheta2.*t14.*t15.*t16.*8.64e+8+dtheta1.*dtheta3.*t13.*t14.*t17.*8.64e+8-dtheta1.*dtheta3.*t14.*t15.*t17.*2.88e+8;
et7 = t4.*7.0369885629e+10+t25-t26+tau2.*1.43465618e+10-t2.*t14.*7.5376116e+10-t3.*t15.*7.91290296e+10+t5.*t17.*1.075992135e+10-t4.*t19.*5.085504e+10+t6.*t18.*1.075992135e+10-t15.*tau1.*5.37744e+9-t19.*tau2.*1.0368e+10+dtheta1.*dtheta3.*t17.*3.58664045e+9+dtheta2.*dtheta3.*t18.*3.58664045e+9+t2.*t13.*t15.*8.47584e+10+t3.*t13.*t14.*5.085504e+10;
et8 = t5.*t15.*t16.*-1.209924e+10+t6.*t14.*t16.*6.91524e+9+t7.*t14.*t17.*2.30508e+9+t7.*t15.*t18.*4.03308e+9-t5.*t17.*t19.*7.776e+9-t6.*t18.*t19.*7.776e+9+t13.*t14.*tau1.*3.456e+9+dtheta1.*dtheta2.*t14.*t16.*2.30508e+9-dtheta1.*dtheta2.*t15.*t16.*4.03308e+9+dtheta1.*dtheta3.*t14.*t17.*7.6836e+8-dtheta1.*dtheta3.*t17.*t19.*2.592e+9-dtheta2.*dtheta3.*t18.*t19.*2.592e+9+t5.*t13.*t14.*t16.*7.776e+9;
et9 = t6.*t13.*t15.*t16.*-7.776e+9-t7.*t13.*t14.*t18.*2.592e+9-t7.*t13.*t15.*t17.*2.592e+9+dtheta1.*dtheta2.*t13.*t14.*t16.*2.592e+9-dtheta1.*dtheta2.*t13.*t15.*t16.*2.592e+9-dtheta1.*dtheta3.*t13.*t15.*t17.*8.64e+8;
f = [dtheta1;dtheta2;dtheta3;t30.*(et1+et2+et3).*-1.2e+2;t30.*(et4+et5+et6).*-2.4e+1;t30.*(et7+et8+et9).*-2.4e+1];
end
